---
all:
  vars:
    ansible_connection: ssh
    ansible_user: ec2-user
    ansible_become: true
    ansible_ssh_private_key_file: /home/ec2-user/kafka-update-so/ramalho.cer
    installation_method: archive
    confluent_archive_file_source: /home/ec2-user/binaries/confluent-7.4.1.zip
    confluent_archive_file_remote: false
    kafka_broker_configure_multiple_listeners: true
    kafka_broker_custom_listeners:
      broker:
        name: BROKER
        port: 9091
        ssl_enabled: false
        ssl_mutual_auth_enabled: false
        sasl_protocol: none
      internal:
        name: INTERNAL
        port: 9092
        ssl_enabled: false
        ssl_mutual_auth_enabled: false
        sasl_protocol: none
      client_listener:
        name: CLIENT
        port: 9093
        ssl_enabled: false
        ssl_mutual_auth_enabled: false
        sasl_protocol: none

zookeeper:
  hosts:
    ip-10-0-1-100.us-east-2.compute.internal:
    ip-10-0-9-7.us-east-2.compute.internal:
    ip-10-0-2-41.us-east-2.compute.internal:

kafka_broker:
  hosts:
    ip-10-0-8-227.us-east-2.compute.internal:
      kafka_broker_custom_listeners:
          client_listener:
            hostname: 3.137.187.50
    ip-10-0-8-210.us-east-2.compute.internal:
      kafka_broker_custom_listeners:
          client_listener:
            hostname: 3.17.76.48
    ip-10-0-0-233.us-east-2.compute.internal:
      kafka_broker_custom_listeners:
          client_listener:
            hostname: 18.189.170.153