version: "2"
services:
  jaeger-all-in-one:
    container_name: jaeger-all-in-one
    image: jaegertracing/all-in-one:1.40
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
      
  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:Z
    ports:
      - "13133:13133" # Health_check extension
      - "4317:4317"   # OTLP gRPC receiver
    depends_on:
      - jaeger-all-in-one

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'sampledb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'redhat'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'redhat'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'redhat'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
 
    